### ISSUE TITLE
Create more Conditions

### ISSUE THREAD

**Issue by jamestmartin** [HazenRobotics/ftc_app#4]
We are using the Condition class to manage autonomous-mode functionality now, so it'd be convenient to have Conditions for common tasks so we don't have to rewrite them in an anonymous class every time we need them.

A good place to start might be to take existing anonymous Conditions and putting them into their own files. Aside from that, we should build at least these Conditions:
* A timer that performs an action for a fixed period of time
* A Condition using the range sensor that is true until the robot travels a fixed distance
* Another one using the gyro to turn a fixed angle

**Comment by HazenRobotics** [comment]
Merged Range Condition into master

**Comment by HazenRobotics** [comment]
Competed 3 (Range, Timer and GyroTurn) Conditionals with Java Doc
